"""agrego_detalle_id_autoincremental_a_detalles_pedido

Revision ID: 4b2c1a8d3e5f
Revises: 2a6aaf476cba
Create Date: 2026-06-13 22:05:00.000000

Permite que un mismo producto aparezca múltiples veces en un pedido
con distintas personalizaciones (ej: Pizza calabresa SIN cebolla + Pizza
calabresa SIN pepperoni). La PK anterior (pedido_id, producto_id) impedía
esto al violar la restricción de unicidad.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4b2c1a8d3e5f'
down_revision: Union[str, Sequence[str], None] = '2a6aaf476cba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # -------------------------------------------------------------------------
    # 1. Agregar columna detalle_id como BIGSERIAL (autoincremental)
    #    Se genera automáticamente con el valor secuencial para las filas
    #    existentes (detalle_id = row_number por pedido_id, producto_id).
    # -------------------------------------------------------------------------
    op.add_column(
        'detalles_pedido',
        sa.Column('detalle_id', sa.BigInteger(), autoincrement=True, nullable=False)
    )

    # -------------------------------------------------------------------------
    # 2. Poblar detalle_id para las filas existentes usando una secuencia.
    #    Creamos una secuencia temporal para cubrir el rango de IDs existentes.
    # -------------------------------------------------------------------------
    # Obtener el valor máximo actual de detalle_id (0 si no existe aún en la secuencia)
    # PostgreSQL autoincrementará las nuevas filas, pero para las existentes
    # necesitamos setear valores únicos.
    # Usamos una UPDATE con row_number por pedido para mantener orden determinista.
    op.execute("""
        CREATE SEQUENCE IF NOT EXISTS tmp_detalle_id_seq START 1;
    """)
    op.execute("""
        UPDATE detalles_pedido
        SET detalle_id = nextval('tmp_detalle_id_seq'::regclass)
        WHERE detalle_id IS NULL
        OR detalle_id = 0
        OR detalle_id IS NOT NULL AND detalle_id < 0;
    """)
    # Para filas que ya tengan detalle_id set (por si acaso), solo asegurar no nulos
    op.execute("""
        UPDATE detalles_pedido
        SET detalle_id = COALESCE(detalle_id, nextval('tmp_detalle_id_seq'::regclass))
        WHERE detalle_id IS NULL;
    """)
    op.execute("DROP SEQUENCE IF EXISTS tmp_detalle_id_seq;")

    # -------------------------------------------------------------------------
    # 3. Hacer la columna NOT NULL ahora que tiene valores únicos
    # -------------------------------------------------------------------------
    op.alter_column('detalles_pedido', 'detalle_id', nullable=False)

    # -------------------------------------------------------------------------
    # 4. Agregar la nueva PK como constraint (no como IDENTITY para evitar
    #    conflictos con la secuencia de SQLModel/SQLAlchemy).
    #    ALTER COLUMN + ADD CONSTRAINT es la forma portable.
    # -------------------------------------------------------------------------
    op.execute("""
        ALTER TABLE detalles_pedido
        ALTER COLUMN detalle_id
        SET DEFAULT nextval('detalles_pedido_detalle_id_seq'::regclass);
    """)
    op.execute("""
        ALTER TABLE detalles_pedido
        ALTER COLUMN detalle_id
        ADD GENERATED BY DEFAULT AS IDENTITY (
            SEQUENCE NAME detalles_pedido_detalle_id_seq
            START WITH 1
            INCREMENT BY 1
            NO MINVALUE
            NO MAXVALUE
            CACHE 1
        );
    """)

    # -------------------------------------------------------------------------
    # 5. Eliminar la PK compuesta anterior
    # -------------------------------------------------------------------------
    op.execute("""
        ALTER TABLE detalles_pedido
        DROP CONSTRAINT IF EXISTS detalles_pedido_pkey;
    """)

    # -------------------------------------------------------------------------
    # 6. Agregar la nueva PK sobre detalle_id
    # -------------------------------------------------------------------------
    op.execute("""
        ALTER TABLE detalles_pedido
        ADD CONSTRAINT detalles_pedido_pkey PRIMARY KEY (detalle_id);
    """)


def downgrade() -> None:
    # Reversión: volver a PK compuesta (pedido_id, producto_id)
    op.execute("""
        ALTER TABLE detalles_pedido
        DROP CONSTRAINT IF EXISTS detalles_pedido_pkey;
    """)
    op.execute("""
        ALTER TABLE detalles_pedido
        DROP COLUMN IF EXISTS detalle_id;
    """)
    op.execute("""
        ALTER TABLE detalles_pedido
        ADD CONSTRAINT detalles_pedido_pkey PRIMARY KEY (pedido_id, producto_id);
    """)