"""creo_tabla_direccion_entrega

Revision ID: 722520f41860
Revises: 2a6aaf476cba
Create Date: 2026-05-04 22:46:47.552488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '722520f41860'
down_revision: Union[str, Sequence[str], None] = '2a6aaf476cba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('direccion_entrega',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('calle', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('numero', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('piso', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('departamento', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('localidad', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('referencias', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('es_predeterminada', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('direccion_entrega')
    # ### end Alembic commands ###
