"""Dominio 2 completo: Productos Categorias e Ingredientes

Revision ID: c8f585967ecb
Revises: e9aa58fd7323
Create Date: 2026-04-17 23:14:36.591342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'c8f585967ecb'
down_revision: Union[str, Sequence[str], None] = 'e9aa58fd7323'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('producto_categoria',
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('producto_id', 'categoria_id')
    )
    op.create_table('producto_ingrediente',
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('ingrediente_id', sa.Integer(), nullable=False),
    sa.Column('es_removible', sa.Boolean(), nullable=False),
    sa.Column('precio_adicional', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['ingrediente_id'], ['ingrediente.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('producto_id', 'ingrediente_id')
    )
    op.drop_table('productoingrediente')
    op.drop_table('productocategoria')
    op.drop_index(op.f('ix_ingrediente_nombre'), table_name='ingrediente')
    op.create_index(op.f('ix_ingrediente_nombre'), 'ingrediente', ['nombre'], unique=True)
    op.add_column('producto', sa.Column('precio_base', sa.Float(), nullable=False))
    op.add_column('producto', sa.Column('es_personalizable', sa.Boolean(), nullable=False))
    op.add_column('producto', sa.Column('imagen_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('producto', sa.Column('stock_disponible', sa.Integer(), nullable=False))
    op.add_column('producto', sa.Column('activo', sa.Boolean(), nullable=False))
    op.alter_column('producto', 'descripcion',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_producto_nombre'), table_name='producto')
    op.create_index(op.f('ix_producto_nombre'), 'producto', ['nombre'], unique=True)
    op.drop_column('producto', 'precio')
    op.drop_column('producto', 'disponible')
    op.drop_column('producto', 'stock')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('producto', sa.Column('stock', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('producto', sa.Column('disponible', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('producto', sa.Column('precio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_producto_nombre'), table_name='producto')
    op.create_index(op.f('ix_producto_nombre'), 'producto', ['nombre'], unique=False)
    op.alter_column('producto', 'descripcion',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('producto', 'activo')
    op.drop_column('producto', 'stock_disponible')
    op.drop_column('producto', 'imagen_url')
    op.drop_column('producto', 'es_personalizable')
    op.drop_column('producto', 'precio_base')
    op.drop_index(op.f('ix_ingrediente_nombre'), table_name='ingrediente')
    op.create_index(op.f('ix_ingrediente_nombre'), 'ingrediente', ['nombre'], unique=False)
    op.create_table('productocategoria',
    sa.Column('producto_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('categoria_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], name=op.f('productocategoria_categoria_id_fkey')),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], name=op.f('productocategoria_producto_id_fkey')),
    sa.PrimaryKeyConstraint('producto_id', 'categoria_id', name=op.f('productocategoria_pkey'))
    )
    op.create_table('productoingrediente',
    sa.Column('producto_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ingrediente_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ingrediente_id'], ['ingrediente.id'], name=op.f('productoingrediente_ingrediente_id_fkey')),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], name=op.f('productoingrediente_producto_id_fkey')),
    sa.PrimaryKeyConstraint('producto_id', 'ingrediente_id', name=op.f('productoingrediente_pkey'))
    )
    op.drop_table('producto_ingrediente')
    op.drop_table('producto_categoria')
    # ### end Alembic commands ###
