"""Actualizar tabla usuario con password en texto plano

Revision ID: c9ae320f08b6
Revises: c8f585967ecb
Create Date: 2026-04-20 18:11:41.874195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'c9ae320f08b6'
down_revision: Union[str, Sequence[str], None] = 'c8f585967ecb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    
   
    op.execute("DROP TABLE rol CASCADE")
    
    # Enum
    op.execute("CREATE TYPE rolusuario AS ENUM ('CLIENTE', 'ADMIN', 'GESTOR_STOCK', 'GESTOR_PEDIDOS')")
    
    # columnas a la tabla usuario
    op.add_column('usuario', sa.Column('password', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.add_column('usuario', sa.Column('rol', sa.Enum('CLIENTE', 'ADMIN', 'GESTOR_STOCK', 'GESTOR_PEDIDOS', name='rolusuario'), nullable=False))
    op.add_column('usuario', sa.Column('eliminado_en', sa.DateTime(), nullable=True))
    
    # columnas viejas que ya no sirven
    op.drop_column('usuario', 'telefono')
    op.drop_column('usuario', 'rol_id')
    op.drop_column('usuario', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('usuario', sa.Column('rol_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('usuario', sa.Column('telefono', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('usuario_rol_id_fkey'), 'usuario', 'rol', ['rol_id'], ['id'])
    op.drop_column('usuario', 'eliminado_en')
    op.drop_column('usuario', 'rol')
    op.drop_column('usuario', 'password')
    op.create_table('rol',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('rol_pkey'))
    )
    op.create_index(op.f('ix_rol_nombre'), 'rol', ['nombre'], unique=True)
    # ### end Alembic commands ###
