"""Refactor modulo categoria

Revision ID: e9aa58fd7323
Revises: 5738ddf56dd2
Create Date: 2026-04-17 22:29:19.755216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'e9aa58fd7323'
down_revision: Union[str, Sequence[str], None] = '5738ddf56dd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_categoria_nombre'), table_name='categoria')
    op.create_index(op.f('ix_categoria_nombre'), 'categoria', ['nombre'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_categoria_nombre'), table_name='categoria')
    op.create_index(op.f('ix_categoria_nombre'), 'categoria', ['nombre'], unique=False)
    # ### end Alembic commands ###
